#PBS -l nodes=1:pbd:ppn=1
#PBS -l nodes+=1:tools:ppn=1
#PBS -N model_0.15
#PBS -S /bin/bash
#PBS -m abe
#PBS -M xfds@pbd.tools
#PBS -j oe

# load required modules
module load fds/6.7.7

# change to the working directory
cd $PBS_O_WORKDIR

# set MPI variables
export I_MPI_PIN=1
export I_MPI_PIN_MODE=pm
export OMP_NUM_THREADS=1
export MPI_PPN=$(($PBS_NUM_PPN / $OMP_NUM_THREADS))
export MPI_NP=$(($PBS_NP / $OMP_NUM_THREADS))

# run fds in parallel
mpiexec -np $MPI_NP fds_mpi model_0.15.fds
