name: Release
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        poetry-version: [1.1.13]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2z
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install --user --upgrade nox
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}

    - name: Run tests
      run: nox

    - name: Build Package
      run: poetry build

    - name: Push to PyPI
      run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
