name: Tests
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Nox
      uses: excitedleigh/setup-nox@v2.0.0

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.0.0

    - name: Run tests
      run: nox
