name: Tests
on:
  - push
  - pull_request

jobs:


  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        poetry-version: [1.1.12]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: excitedleigh/setup-nox@v2.0.0
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - run: nox -s tests


  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        poetry-version: [1.1.12]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: excitedleigh/setup-nox@v2.0.0
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - run: nox --sessions test coverage
      env:
        CODECOV_TOKEN: ${CODECOV_TOKEN}


  black:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        poetry-version: [1.1.12]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: excitedleigh/setup-nox@v2.0.0
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - run: nox -s black


  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        poetry-version: [1.1.12]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: excitedleigh/setup-nox@v2.0.0
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - run: nox -s lint


  safety:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        poetry-version: [1.1.12]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: excitedleigh/setup-nox@v2.0.0
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - run: nox -s safety


  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        poetry-version: [1.1.12]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: excitedleigh/setup-nox@v2.0.0
    - uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - run: nox -s mypy
